// All new homepage copy, in both languages, kept in one place.
// (Arabic was drafted to match the tone of your existing translations —
// worth a quick read-through by a native speaker before launch.)
export const HOME_TEXT = {
  en: {
    heroEyebrow: "Generals Zero Hour · Ranked community",
    heroLine1: "Commander",
    heroJoin: "Join",
    heroTag: "COM | TEAM",
    heroSub: "Replays · Strategies · Clan · Tournaments · Community",
    joinClan: "Join our clan",
    watchLatest: "Watch the latest video",
    statPlayers: "Players",
    statMatches: "Matches",
    statReplays: "Replays",
    barLeft: "Field report",
    barRight: "Broadcasting",
    barScroll: "Scroll",
    barLangs: "English · العربية",
    facts: ["2v2 · 3v3 · 4v4 ladder", "FFA ladder", "Replay library", "Tournaments", "Maps and mods", "English and Arabic"],
    waysEyebrow: "Start here",
    waysTitle: "Three ways in",
    ways: [
      { n: "01", title: "Play ranked", desc: "Team and FFA ladders with ratings that reset every season.", cta: "Open the ladder" },
      { n: "02", title: "Study replays", desc: "Download professional Zero Hour matches.", cta: "Browse the library" },
      { n: "03", title: "Compete", desc: "Events, rankings and winners.", cta: "See tournaments" },
    ],
    frontEyebrow: "Current standings",
    frontTitle1: "Top",
    frontTitle2: "commanders",
    team: "Team",
    ffa: "FFA",
    fullBoard: "Full leaderboard",
    frontEmpty: "No ranked players yet this season.",
    joinEyebrow: "Recruiting now",
    joinTitle1: "Your seat",
    joinTitle2: "is waiting.",
    joinText: "Looking to compete, contribute, or help run the clan? Apply now and we'll get back to you on Discord.",
    apply: "Apply now",
    discord: "Join the Discord",
    exploreEyebrow: "Explore",
  },
  ar: {
    heroEyebrow: "جنرالات الساعة الصفر · مجتمع تنافسي",
    heroLine1: "Commander",
    heroJoin: "انضم إلى",
    heroTag: "COM | TEAM",
    heroSub: "ترتيب تنافسي ومكتبة إعادات وبطولات لمن لا يزال يلعب جنرالات الساعة الصفر.",
    joinClan: "انضم إلى الكلان",
    watchLatest: "شاهد آخر فيديو",
    statPlayers: "لاعبون",
    statMatches: "مباريات",
    statReplays: "إعادات",
    barLeft: "تقرير ميداني",
    barRight: "بث مباشر",
    barScroll: "مرّر للأسفل",
    barLangs: "English · العربية",
    facts: ["تصنيف 2v2 · 3v3 · 4v4", "تصنيف FFA", "مكتبة الإعادات", "البطولات", "الخرائط والتعديلات", "الإنجليزية والعربية"],
    waysEyebrow: "ابدأ من هنا",
    waysTitle: "ثلاث طرق للانضمام",
    ways: [
      { n: "01", title: "العب تنافسياً", desc: "تصنيفات الفرق والـ FFA مع تقييمات تُعاد كل موسم.", cta: "افتح الترتيب" },
      { n: "02", title: "ادرس الإعادات", desc: "حمّل مباريات احترافية من Zero Hour.", cta: "تصفح المكتبة" },
      { n: "03", title: "نافس", desc: "فعاليات وترتيب وفائزون.", cta: "شاهد البطولات" },
    ],
    frontEyebrow: "الترتيب الحالي",
    frontTitle1: "أفضل",
    frontTitle2: "القادة",
    team: "الفرق",
    ffa: "FFA",
    fullBoard: "لوحة الترتيب الكاملة",
    frontEmpty: "لا يوجد لاعبون مصنَّفون بعد هذا الموسم.",
    joinEyebrow: "التجنيد مفتوح",
    joinTitle1: "مقعدك",
    joinTitle2: "ينتظرك.",
    joinText: "تريد المنافسة أو المساهمة أو المساعدة في إدارة الكلان؟ قدّم الآن وسنتواصل معك على ديسكورد.",
    apply: "قدّم الآن",
    discord: "انضم إلى ديسكورد",
    exploreEyebrow: "استكشف",
  },
} as const;

export type HomeLocale = keyof typeof HOME_TEXT;
